[package]
name = "hello-world-derive"
version = "0.1.0"
authors = ["Tyler Thrailkill <tyler.thrailkill@promontech.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.12", features = ["full", "derive"] }
quote = "0.4.2"
proc-macro2 = { version = "0.2", features = ["nightly"] }
